apiVersion: v1
kind: Service
metadata:
  labels:
    component: prom2teams
  name: prom2teams
  namespace: default
spec:
  clusterIP: 10.233.8.189
  externalTrafficPolicy: Cluster
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    component: prom2teams
  sessionAffinity: None
  type: LoadBalancer
