---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom2teams
  namespace: default
  labels:
    component: prom2teams
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: prom2teams
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - prom2teams
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: prom2teams
        image: podnov/prom2teams:latest
        imagePullPolicy: Always
        env:
        - name: PROM2TEAMS_CONNECTOR
          value: "<provide me>"
        - name: PROM2TEAMS_HOST
          value: "0.0.0.0"
        - name: PROM2TEAMS_PORT
          value: "8089"
